  - name: Installing Prerequisites for Elastic Stack Ubuntu
    apt:
      name:
        - openjdk-8-jdk
        - apt-transport-https
      state: latest


  - name: Installing Elastic Stack
    apt:
      name:
        - elasticsearch
        - logstash
        - kibana
      state: latest


